name: copybara

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test wilmol/copybara-action
        uses: wilmol/copybara-action@master
        with:
          git_name: wilmol
          git_email: willjoemolloy@gmail.com
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_known_hosts: ${{ secrets.KNOWN_HOSTS }}
